### ISSUE TITLE
Requests Page

### ISSUE THREAD

**Issue by AmrHosam** [AmrHosam/SE2018G22#9]
1- All fields should be required
2- Use Datepicker in jQuery instead of the text field in date of birth

**Comment by omarnagah** [comment]
https://github.com/AmrHosam/SE2018G22/blob/master/prototype/final/project/formsPage.php

**Comment by omarnagah** [comment]
https://github.com/AmrHosam/SE2018G22/blob/master/prototype/final/project/formsPage.php
